### ISSUE TITLE
Role to target mapping

### ISSUE THREAD

**Issue by dannyk81** [camptocamp/prometheus-puppetdb#5]
Currently, the tool is built to provide dynamic scrape target configuration for the collectd agent (exporter?), however I'm considering to add an option whereis we can map `roles` in Puppet to exporters for which a scrape is required, for example:

```
- exporter: <exporter-1>:
  port: <port number>
  path: <metrics path>
  roles:
    - <role-1>
    - <role-2>
- exporter: <exporter-2>:
  port: <port number>
  path: <metrics path>
  roles:
    - <role-1>
    - <role-2>
```

WDYT?

/EDIT: Changed the yaml above, I think it makes more sense to have roles associated to exporters, the scrape config will be the exporters, and it will list in the targets all the nodes that belong to the listed roles.

**Comment by raphink** [comment]
I'm not sure to understand how that would work. Can you give a concrete example of PuppetDB nodes and how they would be mapped?

**Comment by dannyk81** [comment]
@raphink thanks for replying! sorry that I wasn't clear, let me try to clarify.

All nodes in Puppet are assigned a Role in Hiera, this Role name is unique and identifies the type of Server/Node that is being managed.

PuppetDB query: `facts[certname,value] {name='role'}`

JSON Result (sample):
```
[
  {
    "certname": "metricst-02.<domain>",
    "value": "metricst"
  },
  {
    "certname": "elasticdata-01.<domain>",
    "value": "elasticdata"
  }
]
```

Since all nodes of the same `role` are identical in terms of functionality, they will have a set of Prometheus exporters required to monitor them.

For example:
* metricst: node_exporter, cadvisor, graphite_exporter
* elasticdata: node_exporter, elasticsearch_exporter

My idea was to create a mapping (via a yaml config file), to map each exporter (node_exporter, elasticsearch_exporter, etc...) to a list of Roles that are running them (i.e. nodes in that role that need to be scraped).

Given the above sample, the mapping will look like so:
```
- exporter: node_exporter
  port: 9100
  path: "/metrics"
  roles:
    - metricst
    - elasticdata
- exporter: cadvisor
  port: 8080
  path: "/metrics"
  roles:
    - metricst
- exporter: graphite_exporter
  port: 9108
  path: "/metrics"
  roles:
    - metricst
- exporter: elasticsearch_exporter
  port: 9200
  path: "/metrics"
  roles:
    - elasticdata
```

Using the above, this tool will generate separate Scrape Configs per each Exporter (i.e. node_exporter, cadvisor, etc...) and include in the targets all the nodes whose role are associated with that said exporter.

The general best practice/approach in prometheus is to group the Scrape Jobs by the exporter type (i.e. node-exporter, cadvisor, etc...) and include under each Job the targets that should be scraped, the above should align with that nicely.
