### ISSUE TITLE
How to include the scrape configs in conf.d in Prometheus main configuration?

### ISSUE THREAD

**Issue by dannyk81** [camptocamp/prometheus-puppetdb#7]
@raphink I'm a bit confused about this... the tool generates the scrape configs in the conf.d directory but how are these expected to be included into prometheus main configuration?

AFAIK, there's no include option in prometheus (except for rules and file_sd targets).

Am I missing something?

**Comment by raphink** [comment]
Good question!

After investigating a bit, it turns out this is indeed not standard. We use a little helper container to merge all confs in `conf.d`: https://github.com/camptocamp/prometheus-config-merger

**Comment by dannyk81** [comment]
Wow, OK - now it makes sense 👍 

I'n wondering if we can avoid this, the only parameter which is set in the scrape_config level is the `metrics_path` but if we set it as a `target label` perhaps we could define it using relabling.

**Comment by dannyk81** [comment]
Here's an example of how this works.

in `targets.yaml` file we add a new label per target, specifying the metrics path:

```
- targets:
  - <ip>:<port>
  labels:
    certname: server1.domain.com
    host: server1.domain.com
    metrics_path: /metrics1
    job: blabla1
- targets:
  - <ip>:<port>
  labels:
    certname: server2.domain.com
    host: server2.domain.com
    metrics_path: /metrics1
    job: blabla1
```

in prometheus configuration, we define the a `relabel_configs` like so:
```
  - job_name: 'prometheus-puppetdb'  # This is a default value, it is mandatory.
    file_sd_configs:
      - files:
        - targets.yaml
    relabel_configs:
    - source_labels: [metrics_path]
      regex: (.+)
      target_label: __metrics_path__
```

and the result is:
![image](https://user-images.githubusercontent.com/24274156/35102147-0c5cb18e-fc30-11e7-925d-e2a47ccf3cb1.png)

The same method can be applied for `scheme` value as well, in case the exporter in question is accessed via `https`.

I think this approach simplifies the work needed to be done by this tool and gives more flexibility, also it's very common to use this kind of pattern in Prometheus, for [example](https://github.com/prometheus/prometheus/blob/ab7c54e2c83be89f4aa612c656475b480c8aba2e/documentation/examples/prometheus-kubernetes.yml#L83-L86) in the Kubernetes prometheus configuration.

P.S. these labels can be dropped after relabling, in order to not store them in each metric.

**Comment by dannyk81** [comment]
Here's a complete `relabel_configs` I intend to use:
```
    relabel_configs:
    - source_labels: [metrics_path]
      regex: (.+)
      action: replace
      target_label: __metrics_path__
    - source_labels: [scheme]
      regex: (.+)
      action: replace
      target_label: __scheme__
    - source_labels: [certname]
      regex: (.+?)\.(.+)
      action: replace
      target_label: instance
      replacement: ${1}
    - regex: ^metrics_path$|^scheme$
      action: labeldrop
```

The above will set the `metrics_path` & `scheme` per target and set the `instance` to the hostname part extracted from `certname`, and then drop our "internal" `metrics_path` & `scheme` labels.

I tested the above and it works really well.

**Comment by mcanevet** [comment]
Well I just saw your relabeling comment after the release of `v0.6.0`. I didn't know we can override `metrics_path` and `scheme` that way (is it also possible for credentials?).
I think it's a good idea, so that we only have one target file and we don't touch the main configuration file. I'll try to implement this in the next release (unless you want to do it first). But at least, now we can have more than one exporter per node.

**Comment by dannyk81** [comment]
These are the internal labels I'm sure we can manipulate through relabeling:
```
MetricNameLabel = "__name__"
SchemeLabel = "__scheme__"
AddressLabel = "__address__"
MetricsPathLabel = "__metrics_path__"
```
source: https://github.com/prometheus/common/blob/0d5de9d6d8629cb8bee6d4674da4127cd8b615a3/model/labels.go#L32-L46

However, there's also the `__param` label prefix, which I believe can be used to set the authentication values (i.e. username, password) by adding the following labels to the targets, like so:
```
- targets:
  - x.x.x.x:1234
- labels:
    __param_password: 'somepass'
    __param_username: 'someuser'
```

I have not tested/validated this, but I believe this may work.

In any case, this needs to done/considered very carefully as this will include the credentials in the sd files...
